# ROOTDIR := $(realpath $(MAKEDIR)../relative/path/to/root)

## Includes of Makefiles needed to build autoconf project
$(eval $(call remote_include,program,/path/to/Makefile))

## Assign autoconf variables here
program_VPATH := /path/to/remotes
program_OBJECTS :=
program_LDADD :=
program_DEPENDENCIES :=

LDADD :=

## Insert any special dependencies here
# my.fuzzer: my.o missing-symbols.o

## Make custom calls to macros like $(call link) here
#$(eval $(call link,LINK,mytarget,mytarget.o mydep.o,$(LDADD),/path/prefix/to/program/objects/and/makefile,program_OBJECTS,program_LDADD,program_DEPENDENCIES))
