# Includes of Makefiles needed to build autoconf project
$(eval $(call remote_include,program,/path/to/Makefile))

# Assign autoconf variables here
program_VPATH := /path/to/remotes
program_OBJECTS :=
program_LDADD :=
program_DEPENDENCIES :=

LDADD :=

# Make custom calls to macros like $(call link) here
#$(eval $(call link,LINK,mytarget,mytarget.o,$(LDADD),/path/to/program,program_OBJECTS,program_LDADD,program_DEPENDENCIES)
